__author__ = 'hung.duong'

title_screen_ID = 'com.quanta.childsettings:id/txt_title_text'
home_ID = 'com.quanta.childsettings:id/btn_title_home'
add_another_child_ID = 'com.quanta.childsettings:id/layout_add_profile'
first_child_Name = 'Vcc  >'
view_usage_detail_link_ID = 'com.quanta.childsettings:id/btn_usage_details'
edit_profile_link_ID = 'com.quanta.childsettings:id/btn_edit'
profile_permission_Name = 'Permissions  >'
time_controls_Name = 'Time Controls OFF  >'
